project_id = "lybclzqgvnlphltjlmwg"

[functions.n8n-api]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.cleanup-stale-sessions]
verify_jwt = false

[functions.create-user]
verify_jwt = false
